### ISSUE TITLE
delete modal show and hide

### ISSUE THREAD

**Issue by anditsung** [spatie/nova-backup-tool#106]
after click delete the delete modal will show and hide
using version 4.1.6
nova 3.20

**Comment by freekmurze** [comment]
@quintenbuis could you take a look at this?

**Comment by quintenbuis** [comment]
Hi @AdrianMrn,

I've tried reproducing the bug but I can't.

Have you tried deleting browser cache? Or deleting the folder `vendor/spatie/nova-backup-tool` and run `composer update spatie/nova-backup-tool` again?

**Comment by anditsung** [comment]
@quintenbuis seems to be browser cache issue. after emply cache there is now show and hide issue anymore
