### ISSUE TITLE
Multiple monitors with same disk but different names don't show backups

### ISSUE THREAD

**Issue by Gummibeer** [spatie/nova-backup-tool#107]
The dropdown shows the same disk two times but doesn't show any files as it doesn't use the name from the monitors config which it uses to retrieve the disks.
I think that the `name` should be displayed and used to retrieve files as well.

Something like this code-snippet could work to instantiate all backup destinations.

```php
$disk = 'backups';

$names = collect(config('backup.monitor_backups'))
  ->filter(fn(array $monitor) => in_array($disk, $monitor['disks']))
  ->pluck('name')
  ->unique()
  ->all();
```

<img width="811" alt="Bildschirmfoto 2021-04-13 um 21 14 35" src="https://user-images.githubusercontent.com/6187884/114609877-93e62a00-9c9f-11eb-8d40-0fc2d47cd1c3.png">
<img width="1137" alt="Bildschirmfoto 2021-04-13 um 21 13 48" src="https://user-images.githubusercontent.com/6187884/114609878-95afed80-9c9f-11eb-9abe-2dc581ef56f4.png">
<img width="941" alt="Bildschirmfoto 2021-04-13 um 21 13 39" src="https://user-images.githubusercontent.com/6187884/114609882-96488400-9c9f-11eb-8e99-91897fed4fe5.png">

**Comment by jamespavett** [comment]
I have the exact same issue, would be good if the name could be shown in the frontend table alongside the disk
