### ISSUE TITLE
TypeError: this.backupStatuses.map is not a function

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/nova-backup-tool#11]
Just tried this out in a project that has backups already set up, but getting an error (every second) when it tries to poll for new backups:

```
vendor.js?id=90728b2f4840cb3e821d:1 TypeError: this.backupStatuses.map is not a function
    at a.disks (BackupTool:1)
    at Ne.I3G/.Ne.get (vendor.js?id=90728b2f4840cb3e821d:1)
    at Ne.I3G/.Ne.evaluate (vendor.js?id=90728b2f4840cb3e821d:1)
    at a.disks (vendor.js?id=90728b2f4840cb3e821d:1)
    at a.render (BackupTool:1)
    at a.I3G/.t._render (vendor.js?id=90728b2f4840cb3e821d:1)
    at a.<anonymous> (vendor.js?id=90728b2f4840cb3e821d:1)
    at Ne.I3G/.Ne.get (vendor.js?id=90728b2f4840cb3e821d:1)
    at Ne.I3G/.Ne.run (vendor.js?id=90728b2f4840cb3e821d:1)
    at Se (vendor.js?id=90728b2f4840cb3e821d:1)
```

As the vendor.js file is minimized, I can't really figure out how to debug this any further.

Perhaps something I forgot to run during the installation process?

**Comment by freekmurze** [comment]
Are you able to create and monitor backups from the command line?

**Comment by sebastiaanluca** [comment]
Yep, works without issues. They are, however, not healthy (local dev, no backups).

Making a backup fixes the issue, so it seems the backup tool can't handle unhealthy (none, missing, unhealthy, etc) backups?

**Comment by sebastiandedeyne** [comment]
Maybe the API is returning `null` instead of an array in this case?

**Comment by sebastiandedeyne** [comment]
Could you share the backup statusses network request's response?

**Comment by sebastiaanluca** [comment]
`backup-statuses` endpoint:

```
{
    "1":{
        "name":"backups",
        "disk":"dropbox",
        "reachable":true,
        "healthy":false,
        "amount":0,
        "newest":"No backups present",
        "usedStorage":"0 KB"
    },
    "0":{
        "name":"backups",
        "disk":"local-backups",
        "reachable":true,
        "healthy":true,
        "amount":1,
        "newest":"5 minutes ago",
        "usedStorage":"16.16 MB"
    }
}
```

Then it only calls `backups?disk=local-backups` (as expected).

**Comment by sebastiandedeyne** [comment]
Yeah, that should be an array, something's going wrong with the json serialization. Will look into this early next week!

**Comment by sebastiaanluca** [comment]
Can confirm the issue exists because it returns an object (or on PHP's side, an associative array but strings instead of inegers as keys) instead of an array when there is more than one backup destination :)

Thanks for the quick response!

**Comment by sebastiandedeyne** [comment]
"Early this week" came later than expected. Just released a patch version that should fix this!
