### ISSUE TITLE
Database only option

### ISSUE THREAD

**Issue by chrisvince** [spatie/nova-backup-tool#15]
Hi!
Great tool for Nova, I love it!
Is there a way to make the default behaviour backup database only? i.e `php artisan backup:run --only-db` command?

Thanks in advance!

**Comment by freekmurze** [comment]
There currently is no option for this. Feel free to submit fully tested, documented and non-breaking PRs that add features to this package.

**Comment by ahmic** [comment]
I have a ready PR for feature to backup only database/files. @freekmurze Should I commit package compiled to production?

**Comment by freekmurze** [comment]
I'll compile the assets myself again, make sure to add an instruction for me to the PR.
