### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by YassineGherbi** [spatie/nova-backup-tool#18]
First of all, I want to say that this tool works really great out of the box!

The only issue I faced for now is that in the `.vue` components there are a few sentences that are not translatable because they're hardcoded instead of using the `__('text')` method that is using is the build in Nova fields/tools. 

If anyone knows a workaround without modifying the source, please let me know!

**Comment by YassineGherbi** [comment]
Just notices that `window.Nova.booting` is used. that means that the global base mixin with the `__('')` method is also accessible. which makes it really easy for users to keep using the Nova localization api for all the tools/fields inside nova (like nova-backup-tool) 

PR is in the making!

**Comment by freekmurze** [comment]
We’ll handle this further in #19
