### ISSUE TITLE
mysqldump issue in Nova Tool, not in Backup Tool

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/nova-backup-tool#36]
Thanks for the great tool! There is one issue that I recently ran into. I've found multiple issue reports for this in the laravel-backup package. In my case, that package is actually working fine, it's only when using the Nova Backup Tool that I get an error.

If I do `php artisan backup:run`, everything works fine and the backup is created. It also shows up in the Nova UI.
Note that for this to work, in `.env` I have set `DB_HOST` to `localhost` instead of `127.0.0.1`, else `backup:run` will fail with the same error message as displayed below.

In config/database I have:
```
'mysql' => [
            'dump' => [ 'dump_binary_path' => '/usr/local/bin/' ]
        ],
```

Now if I click on 'Create Backup' in the Nova Tool, I get the error: `The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2003: Can't connect to MySQL server on '127.0.0.1' (61) when trying to connect.`

This is weird to me as the Laravel Backup package is used in the background to create the backup, and using `backup:run` does work. I'm probably missing something here, do I need to configure something additionally for the Nova Backup Tool with regards to `mysqldump`?

**Comment by freekmurze** [comment]
This is probably a permission problem on your end. Make sure that the process that calls `mysqldump` is allowed to do so.

**Comment by joostvanhoof** [comment]
If `backup:run` works and creates a backup successfully (as per the Nova Backup Tool docs), doesn't that mean `mysqldump` works fine?
I'm confused that this works, but pressing the 'Create Backup' tool in Nova doesn't. For `mysqldump` that would suggest there is a difference between permissions for the Backup Tool and the Nova Tool?
