### ISSUE TITLE
Unable to backup via Nova

### ISSUE THREAD

**Issue by bcorcoran** [spatie/nova-backup-tool#37]
Hi,

I am not getting any errors that I can see, but running `php artisan backup:run` works fine and the nova backup tool sees it, but clicking "Create Backup" from the tool does not work. It says "creating backup in the background" and never finishes. 

I did notice that there are files in the temp dir. SQL, a zip with a temp extension, and a manifest.txt.

**Comment by freekmurze** [comment]
This is probably a permissions issue. Please check if the process that is calling phpmysql is allowed to do so.

**Comment by dangcao410** [comment]
I also encountered the same error. How to fix it?

**Comment by scaleman114** [comment]
I have exactly the same problem, not sure how to fix it?

**Comment by bcorcoran** [comment]
For me, it was not a permissions issue.

My application is an SPA and I had a route that was too eager and was killing all nova-api route requests.

```
// Route for SPA
Route::any('{all}', function() { return view('index'); })
    ->middleware('auth')
    ->where(['all' => '^(?!admin|nova-).*$']);
```

**Comment by bcorcoran** [comment]
I want to add that this is not necessarily spatie's problem, but some error checking in regards to the response data of the nova-api call would have prevented this problem.

**Comment by scaleman114** [comment]
Thanks for the reply, but the problem was on my local dev machine (it works fine on my production server).
You could backup fine using CLI but not through Nova. If you click backup twice in succession you get a partial backup – which seems strange.
