### ISSUE TITLE
The BackupJob is not sent to the queue worker

### ISSUE THREAD

**Issue by Livijn** [spatie/nova-backup-tool#40]
For performance reasons, I only have `mysqldump` installed on my *worker* server. It seems like the backup tool runs the command on my app server, meaning it isn't dispatching the jobs for some reason. 

The exception is thrown from `POST` request to the `BackupsController@create`. I have set my queue connection and it is working for other jobs (`QUEUE_CONNECTION=redis`).

Here is the error: 

> Spatie\DbDumper\Exceptions\DumpFailed
The dump process failed with exitcode 127 : Command not found : sh: 1: mysqldump: not found

Why is the job not sent to the queue?

**Comment by freekmurze** [comment]
Could you try again with the latest version of the package?
