### ISSUE TITLE
problem if there is no local disk

### ISSUE THREAD

**Issue by thomasdominic** [spatie/nova-backup-tool#45]
The tool checks the backups of the Disk = local URL but I do not have a disk named 'local'

**Comment by freekmurze** [comment]
Make sure you've configured the underlying laravel-backup correctly.

**Comment by jaap** [comment]
@thomasdominic had the same issue. The "monitor" disk was not set.
Add the right disk in `backup.php` `monitor_backups.disks` array and clear your config.
`php artisan backup:list` should show you the disk you just added now.
