### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by milewski** [spatie/nova-backup-tool#46]
Hi, I have a fresh nova installation, just by installing this package my machine goes from ~2% CPU usage to 300% CPU, uninstalling this package doesn't make it come back to 2% neither.... only if i remove all my `vendor` folder and do composer install again without including this package then it goes back to ~2%, witch makes me think some dependencies used by this package might be compromised...? dont know might be just me, but do anyone experience the same?

![image](https://user-images.githubusercontent.com/2874967/55790223-79947700-5aee-11e9-9339-9a40beac3366.png)

this is my Dockerfile if you want to try locally:

```
FROM php:fpm-alpine3.9

RUN apk add --no-cache libzip-dev curl git libpng-dev mysql-client
RUN docker-php-ext-install -j$(nproc) zip mbstring pdo pdo_mysql bcmath gd

RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

CMD ["php-fpm"]
```

**Comment by milewski** [comment]
Maybe not related but, Yesterday I was playing with this package on my personal laptop... and left my laptop turned on all the night while I slept, when I woke up at morning my SSD was dead...

**Comment by freekmurze** [comment]
I'm thinking that this problem isn't caused by the package. 

Of course when you're taking a backup, it might consume some cpu.

**Comment by milewski** [comment]
I feel that it may have entered in a loop... and started to backup in-numerous time, when i refresh the backup page it takes forever to load, if i press ESC i see an half rendered page with an enormous list of backups being made

**Comment by erikgaal** [comment]
Hey @milewski, could this be somehow related to #48? Did it happen when you have the Nova Backup Tool opened?

**Comment by milewski** [comment]
@erikgaal yes it happened as soon as I hit the backup button on nova ui... I will try it once again with your pr / without it to see if that was the cause

**Comment by milewski** [comment]
@erikgaal same as before, as soon as I click create backup the CPU goes ~350% no backups were created.. I let it run for around 30min running at ~350%... after when the CPU finally goes down I refresh the backup page and I see this:

![image](https://user-images.githubusercontent.com/2874967/59671840-f4fe5d00-91f0-11e9-95d2-1ae79863cbeb.png)
