### ISSUE TITLE
Cannot delete the backup file

### ISSUE THREAD

**Issue by phuclh** [spatie/nova-backup-tool#49]
The delete button is disabled. I tried to chmod 777 for the backup folder, but it still doesn't work.

<img width="598" alt="Screen Shot 2019-05-25 at 7 29 06 PM" src="https://user-images.githubusercontent.com/6707194/58376633-c8259580-7f23-11e9-8186-666503ea2e61.png">

**Comment by michapixel** [comment]
You'll need another backup, to delete one of them. 

On the one hand this seems clever on the other it would be nice to have at least a config where this can be set (min. amount of backups until you can delete) ...

**Comment by freekmurze** [comment]
By design the last backup cannot be deleted. Going to keep it like it is for now.
