### ISSUE TITLE
not escaping \ in strings?

### ISSUE THREAD

**Issue by giancanuz** [spatie/nova-backup-tool#50]
Hi,
your package is wonderful! 
Anyway, trying to restore a db from a generated backup I've found that some strings are not dumped with proper escaping of \ characters in insert statements. Ex:  'App\User' instead of 'App\\User'
This cause restoring data proceed without issues but imported data looks like 'AppUser' instead of 'App\User'.
Could you please verify it or telling me if there is a proper config option to avoid it?
Thank you.

PS: complete snippet is the following:

`

LOCK TABLES `model_has_roles` WRITE;
/*!40000 ALTER TABLE `model_has_roles` DISABLE KEYS */;
INSERT INTO `model_has_roles` VALUES (1,'App\User',1),(2,'App\User',46),(2,'App\User',59),(4,'App\User',63),(4,'App\User',64),(5,'App\User',47),(6,'App\User',55),(7,'App\User',59);
/*!40000 ALTER TABLE `model_has_roles` ENABLE KEYS */;
UNLOCK TABLES;

`

**Comment by giancanuz** [comment]
related to https://github.com/spatie/laravel-backup/issues/922#issue-455802301

**Comment by freekmurze** [comment]
We'll handle this in the backup package soon.
