### ISSUE TITLE
"Create Backup" not working.

### ISSUE THREAD

**Issue by dangcao410** [spatie/nova-backup-tool#52]
Hi,

I run `php artisan backup:run` works fine and the Nova Backup Tool sees it, but click "Create backup" from the inactive tool.

How to fix it?

**Comment by freekmurze** [comment]
What steps have you taken to investigate this issue? Are you getting an error message?

**Comment by dangcao410** [comment]
It says "create backup" and then doesn't see anything.

**Comment by ahmic** [comment]
I tested it and everything is working as expected. @dangcao410 Maybe your queue is not running?

**Comment by dangcao410** [comment]
> I tested it and everything is working as expected. @dangcao410 Maybe your queue is not running?

Do you know how to fix it?

**Comment by ahmic** [comment]
@dangcao410 Check Console in Chrome dev tools to find out if any error occurred..
