### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by mblanke70** [spatie/nova-backup-tool#69]
Hi,
I'm getting this error:

$ php artisan backup:run
Starting backup...
Dumping database d02d66ab...
Backup failed because The dump process failed with exitcode 1 : General error : Der Befehl ""mysqldump"" ist entweder falsch geschrieben oder konnte nicht gefunden werden.

What went wrong?

Best Regards
Malte

**Comment by freekmurze** [comment]
mysqldump could not be found on your system. There are many reasons that cause this. Please review the other issues that people have reported. There’s a high probabilty that this is caused by your environment, and not this package.
