### ISSUE TITLE
can't install from composer

### ISSUE THREAD

**Issue by Murphz** [spatie/nova-backup-tool#71]
Hello,
I'm using laravel/nova (latest version, freshly installed and licensed one week ago) and spatie/laravel-backup 6.7.6. When I try to add spatie/nova-backup-tool I get this error from composer:

Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for spatie/nova-backup-tool ^3.8 -> satisfiable by spatie/nova-backup-tool[3.8.0].
- spatie/nova-backup-tool 3.8.0 requires laravel/nova ^2.0 -> no matching package found.

**Comment by hemratna** [comment]
Hi @Murphz  
I am facing the same issue. 
Please let me know if you get any solutions.

**Comment by Murphz** [comment]
Nothing yet @hemratna,
will try again during this month, in case I will write some details here.

**Comment by Murphz** [comment]
@hemratna 

The problem is that laravel/nova is a custom local package and the package request fail because it's not found. 

I can't found a solution for just adding spatie/nova-backup-tool in the project root composer file but adding it in the package composer file as a dev requirements, works. 

So, in ./nova/composer.json you need to have:

`"require-dev": {
        // ...
        "spatie/nova-backup-tool": "dev-master"
    },`
