### ISSUE TITLE
Tool is not sending email notifications.

### ISSUE THREAD

**Issue by wemersonrv** [spatie/nova-backup-tool#76]
Hello,

Backup is working fine! I can download the zip file and check it if it's ok... and it is! 

The issue is because i do not receive any email about completion.

I'm using database queue and is working fine for another notifications.

Follow the `notifications` key from backup.php file:

```php
'notifications' => [

        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['email'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['email'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => ['email'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['email'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => ['email'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => ['email'],
        ],

        /*
         * Here you can specify the notifiable to which the notifications should be sent. The default
         * notifiable will use the variables specified in this config file.
         */
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,

        'mail' => [
            'to' => config('tekmab.admin.address'), // My E-mail configured in .env

            'from' => [
                'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
                'name' => env('MAIL_FROM_NAME', 'Example'),
            ],
        ],
```

**Comment by pavel-mironchik** [comment]
Try to replace `email` by `mail`.

**Comment by wemersonrv** [comment]
> Try to replace `email` by `mail`.

Ah yeah, sorry, that was wrong. Tx for the tip.

Replaced now, but still not works. looking for my queue console prints when task is fired, nothing happen... and no one email goes to my mailbox.

**Comment by pavel-mironchik** [comment]
I'd suggest you open such an issue in the https://github.com/spatie/laravel-backup repository. This tool does nothing with notifications, it is spatie/laravel-backup's responsibility.

**Comment by marcoraddatz** [comment]
Don't reference to another config. Either hardcode the email address or use env().
