### ISSUE TITLE
When trying te delete a backup, the backup modal appears and disappears in sequence, not allowing a click

### ISSUE THREAD

**Issue by jberculo** [spatie/nova-backup-tool#85]
Hi,

Thanks for your package! 

I have installed it, and everything works as advertized, except the deletion of backups. When clicking on the delete button, a confirmation modal pops up, and is the closed then again in sequence with the xhr-call in the background. Clicking the confirmation button does not do anything. The strange thing is that all this is working correctly on the test environment (homestead). Update: I was wrong, this is happening on both sites, both homestead and lamp.

But this problem occurring on the staging environment (identical to the live environment), which is an Lamp-environment (ubuntu 18.04/apache2/php7.4.

I have updated laravel and nova to the latest versions, and republished the nova assets. Is there something that I am missing here?

**Comment by Yelles** [comment]
same for me on php 8.

**Comment by xoco70** [comment]
Same here with PHP8.0
