### ISSUE TITLE
Tool page keeps spamming API calls

### ISSUE THREAD

**Issue by WaveHack** [spatie/nova-backup-tool#9]
Here's what I observed when going to this tool page in Nova. I don't think this is intended behavior:

![nova-backup-api-calls](https://user-images.githubusercontent.com/1611537/44629904-3833ca80-a956-11e8-8011-213fd4214a36.gif)

I don't know what's causing it, nor have I started to look into it in the code.

Running on localhost:8000 using `php artisan serve`
Environment: local
Laravel version: 5.6.29
Nova version: 1.0.6
Nova Backup Tool version: 1.0.1

Using Google Cloud Storage package as filesystem: https://github.com/Superbalist/laravel-google-cloud-storage

**Comment by marianvlad** [comment]
They added that to see the backups in "realtime" without refreshing the page.
https://github.com/spatie/nova-backup-tool/blob/master/resources/js/components/BackupTool.vue#L94

**Comment by WaveHack** [comment]
1 second interval seems a bit excessive in my opinion, but I get the idea.

A (potential) issue I'm seeing here is accessing backups at services that require you to pay per X API requests, for example at Google Cloud Storage: https://cloud.google.com/storage/pricing#operations-pricing

What are your thoughts on this?

**Comment by freekmurze** [comment]
Unfortunately polling was the best way to make this feel real time. We could have gone with broadcasting events, but we didn't want users to go through setting that up. Hopefully there will be support out of the box for Laravel Echo in Nova at some point in the future.

There's some server side caching going on too, so a call to external systems will be made once every 5 seconds. I think most users won't leave their nova installation open on the back up screen. I don't think this is a big issue at all.

**Comment by rdrnnr87** [comment]
I hit rate limit on the Dropbox API after a minute or two of the page load.

```
Client error: POST https://api.dropboxapi.com/2/files/list_folder resulted in a 429 Too Many Requests response:
  {"error_summary": "too_many_requests/..", "error": {"reason": {".tag": "too_many_requests"}, "retry_after": 300}}
```
