### ISSUE TITLE
sizeInBytes Error

### ISSUE THREAD

**Issue by ramesesniblick3rd** [spatie/nova-backup-tool#93]
Just done a clean install of this package and noticed after creating a backup, the information in the nova dashboard wasnt displaying due to the following error:

`exception: "Error"
file: "C:\laragon\www\lpnew\vendor\spatie\nova-backup-tool\src\Http\Controllers\BackupsController.php"
line: 31
message: "Call to undefined method Spatie\Backup\BackupDestination\Backup::sizeInBytes()"`

It seems `vendor/spatie/laravel-backup/src/BackupDestination/Backup.php` has only size() and not sizeInBytes(). After changing it to just size() it works.

Edit: It seems it was a recent update to work with laravel-backup 7 which is only available with php 8 and it breaks support for previous versions.

**Comment by quintenbuis** [comment]
Created PR #94  for this.

**Comment by freekmurze** [comment]
Thanks for the PR
